version: 2.1
orbs:
  python: circleci/python@1.0.0

.common-values:
  install-pandoc: &install-pandoc
    name: Install pandoc
    command: sudo apt-get install -y -qq pandoc

.master-branch-filter: &master-branch-filter
  filters:
    branches:
      ignore: master

.tags-only-filter: &tags-only-filter
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /.*/

.requires-lint: &requires-lint
  requires:
    - lint
  <<: *master-branch-filter

.requires-build: &requires-build
  requires:
    - build
  <<: *tags-only-filter

.lint-steps: &lint-steps
  executor: python/default
  steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Check code style (PEP8)
        command: poetry run flake8 src tests

.test-steps: &test-steps
  executor: python/default
  steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Run tests
        command: poetry run tox

.pip-check: &pip-check
  executor: python/default
  steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Run pip check
        command: poetry run pip check

.build: &build
  executor: python/default
  steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Build package
        command: poetry build
    - persist_to_workspace:
        root: .
        paths:
          - dist

.build-docs: &build-docs
  executor: python/default
  steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run: *install-pandoc
    - run:
        name: Build documentation
        command: poetry run sphinx-build -b html source build


.release: &release
  executor: python/default
  steps:
    - attach_workspace:
        at: /tmp/package
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Release package
        command: poetry publish -u $PYPI_USER -p $PYPI_PASSWORD

.type-check: &type-check
  executor: python/default
  steps:
    - checkout
    - python/install-packages:
        pkg-manager: poetry
    - run:
        name: Run type tests
        command: poetry run mypy src tests

jobs:
  lint:
    <<: *lint-steps
  test:
    <<: *test-steps
  pip-check:
    <<: *pip-check
  build:
    <<: *build
  build-docs:
    <<: *build-docs
  release:
    <<: *release
  type-check:
    <<: *type-check

workflows:
  version: 2
  test-all:
    jobs:
      - lint:
          <<: *master-branch-filter
      - test:
          <<: *requires-lint
      - pip-check:
          <<: *requires-lint
      - type-check:
          <<: *requires-lint
      - build-docs:
          <<: *requires-lint
  build-and-release:
    jobs:
      - build:
          <<: *tags-only-filter
      - release:
          <<: *requires-build
