name: build-and-release

on:
  push:
    tags:
      - "**"

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: x64
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Restoring cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Build package
        run: poetry build
      - name: Store build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stored-package
          path: dist
  release:
    name: Release package
    runs-on: ubuntu-latest
    needs:
      - "build"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
          architecture: x64
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Restoring cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: stored-package
      - name: Config PyPI credentials
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - name: Publish package
        run: poetry publish
